// src/utils/words.js

export const SOLUTIONS = [
  'PERRO','GATOS','CASAS','LIBRO','MUNDO','AMIGO','NUBES','SUELO','PIANO','LLAVE',
  'CAMPO','PATIO','RATON','FUEGO','AGUAS','TORRE','OBRAS','PLANO','MAPAS','SILLA',
  'COCHE','FLORE','PUERTA','PELOTA','SOMBR','JUEGO','LUCES','ROCAS','MONTA','NIEVE',
  'MARCO','PLUMA','TELON','BOSQU','LLORO','CIELO','ARENA','ANIMA','HOJAS','SALTO'
];

// Lista de palabras válidas (para validar entradas). Incluye SOLUTIONS + palabras extra
export const WORDS = [
  ...SOLUTIONS,
  'CASCO','BRISA','SONAR','VERDE','AMORO','SALON','VIDAS','MIRAR','CANTO',
  'HUEVO','FRUTA','HABLA','DIBUJ','PLAYA','ARENA','TIERRA','LLENO','VACIO',
  'LECHE','DULCE','LLAMA','TEXTO','CAMIN','SALIR','TIEMO','JUNTA','PANES',
  'BEBER','PESCA','CARRO','RAPID','LARGO','CORTO','FELIZ','TRIST','RIQUE','POBRE',
  'VERAZ','HONRA','MORIR','VIVIR','SONAR','RUIDO','VUELO','APOYO','GRUPO','SOLAR'
];